version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mystore-db-luis
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: mystore_luis
    ports:
      - "3309:3306"
    volumes:
      - mystore-db-luis:/var/lib/mysql
    networks:
      - mystore-network-luis

  categories-backend:
    image: luissagx/categories-backend:latest
    container_name: categories-service-luis
    restart: always
    ports:
      - "8092:8082"
    environment:
      - PORT=8082
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=mystore_luis
      - DB_USER=root
      - DB_PASSWORD=admin
    depends_on:
      - mysql
    networks:
      - mystore-network-luis

  products-backend:
    image: luissagx/products-backend:latest
    container_name: products-service-luis
    restart: always
    ports:
      - "8091:8081"
    environment:
      - PORT=8081
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=mystore_luis
      - DB_USER=root
      - DB_PASSWORD=admin
    depends_on:
      - mysql
    networks:
      - mystore-network-luis

  frontend:
    image: luissagx/super-tienda-frontend:latest
    container_name: tienda-frontend-luis
    restart: always
    ports:
      - "4200:80"
    depends_on:
      - products-backend
      - categories-backend
    networks:
      - mystore-network-luis

volumes:
  mystore-db-luis:

networks:
  mystore-network-luis:
    driver: bridge
