version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: test-db2
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: test
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - test-network

  categories-backend:
    image: luissagx/categories-backend:latest
    container_name: categories-service
    ports:
      - "8082:8082"
    environment:
      - PORT=8082
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=test
      - DB_USER=root
      - DB_PASSWORD=admin
    depends_on:
      - mysql
    networks:
      - test-network

  products-backend:
    image: luissagx/products-backend:latest
    container_name: products-service
    ports:
      - "8081:8081"
    environment:
      - PORT=8081
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=test
      - DB_USER=root
      - DB_PASSWORD=admin
    depends_on:
      - mysql
    networks:
      - test-network

  frontend:
    image: luissagx/super-tienda-frontend:latest
    container_name: tienda-frontend
    ports:
      - "4200:80"
    depends_on:
      - products-backend
      - categories-backend
    networks:
      - test-network

volumes:
  db-data:

networks:
  test-network:
    driver: bridge
